### ISSUE TITLE
Issue on Build

### ISSUE THREAD

**Issue by felixic** [iraizo/truckersmp.ts#228]
I have an Issue when I try to build the project for debug purposes with the npm script

<img width="1058" alt="Bildschirmfoto 2021-07-20 um 21 05 07" src="https://user-images.githubusercontent.com/59060181/126381155-9862969e-37f4-4938-b8c4-7532fba26a22.png">

Same happens when I try building with yarn

**Comment by iraizo** [comment]
Fresh install of yarn, everything works

<img src="https://i.imgur.com/Ka7hEa3.png">

**Comment by felixic** [comment]
Works now, I deleted the node_modules and the package-lock.json and run "nom install"

Thank you
