### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by miniDeathStriker** [iraizo/truckersmp.ts#47]
Currently, the documentation for this module is down? cant access website

**Comment by iraizo** [comment]
Hello, thanks for the interest in this project, currently the site is down because i cannot host it at this time, i will try to in a few days, in the meantime you can grab the documentation by running `yarn run build:docs` and then opening the .html files.

**Comment by iraizo** [comment]
@miniDeathStriker The docs folder is now being hosted on https://truckersmp-ts.vercel.app/  which updates live every commit.
